fedprot:
  counts: protein_counts.tsv
  design: design.tsv
  intensities: protein_groups_matrix.tsv
  sep: '\t'
  
  use_smpc: true
  
  max_na_rate: 0.8
  log_transformed: false

    # label: "Condition"
  target_classes: ["Glu", "Pyr"]
  covariates: []

  result_table: "DPE.csv"
  