fedprot:
  counts: counts.tsv
  design: design.tsv
  intensities: intensities.tsv
  sep: '\t'
  
  use_smpc: false
  
  max_na_rate: 0.8
    # label: "Condition"
  target_classes: ["Pyr", "Glu"]
  covariates: []

  result_table: "DPE.csv"
  